development:
  adapter: mysql2
  database: requisteak_dev
  username: root
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: requisteak_test
  username: root
  password: root
  host: localhost
  encoding: utf8  

production:
  adapter: mysql2
  database: requisteak_db
  username: root
  password: root
  host: localhost
